<a href="https://colab.research.google.com/github/illliyas/Machine-Learning/blob/master/nselib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%capture
!pip install yfinance
!pip install mplfinance
#!pip install TA-Lib

In [2]:
import yfinance as yf
import pandas as pd

In [27]:
stocks=['ARE&M.NS',
'BAJAJ-AUTO.NS',
'DIVISLAB.NS',
'DRREDDY.NS',
'EXIDEIND.NS',
'INFY.NS',
'NATCOPHARM.NS',
'RELIANCE.NS',
'SUNPHARMA.NS',
'TATACHEM.NS',
'TATAMOTORS.NS',
'TATASTEEL.NS',
'TCS.NS',
'TECHM.NS',
'WIPRO.NS',
'ZYDUSLIFE.NS',
'CIPLA.NS',
'ABBOTINDIA.NS',
'HINDUNILVR.NS',
'NESTLEIND.NS',
'TVSMOTOR.NS',
'FINPIPE.NS',
'TATAPOWER.NS',
'GRAUWEIL.BO',
        'ACI.NS',
        'SHYAMMETL.NS',
        'NOCIL.NS',
        'AMIORG.NS',
        'KCP.NS',
        'SANSERA.NS',
        'ROLEXRINGS.NS',
        'AMBUJACEM.NS',
        'BORORENEW.NS'
]

In [28]:
cols = ['exchange','symbol','marketCap','currentPrice','trailingPE','trailingEps','profitMargins','ebitda',
'debtToEquity',
'trailingAnnualDividendYield',
'profitMargins',
'priceToBook',
'financialCurrency',
'earningsQuarterlyGrowth']
stocks_list=[]
for s in stocks:
  print(s)
  dic={}
  stock = yf.Ticker(s)
  for c in cols:
    try:
      dic[c]=stock.info[c]
    except:
      dic[c]=None
  try:
    hist = stock.history(period="1mo")
    hist = hist.sort_index(ascending=False)
    dic['DIFF_30_DAYS']=(hist.iloc[0]['Close']-hist.iloc[-1]['Close'])/hist.iloc[-1]['Close']
    dic['DIFF_7_DAYS']=(hist.iloc[0]['Close']-hist.iloc[5]['Close'])/hist.iloc[5]['Close']
    dic.update(dict(enumerate(map(str, stock.quarterly_income_stmt.loc['Net Income'].values))))
  except:
    None
  stocks_list.append(dic)

ARE&M.NS
BAJAJ-AUTO.NS
DIVISLAB.NS
DRREDDY.NS
EXIDEIND.NS
INFY.NS
NATCOPHARM.NS
RELIANCE.NS
SUNPHARMA.NS
TATACHEM.NS
TATAMOTORS.NS
TATASTEEL.NS
TCS.NS
TECHM.NS
WIPRO.NS
ZYDUSLIFE.NS
CIPLA.NS
ABBOTINDIA.NS
HINDUNILVR.NS
NESTLEIND.NS
TVSMOTOR.NS
FINPIPE.NS
TATAPOWER.NS
GRAUWEIL.BO
ACI.NS
SHYAMMETL.NS
NOCIL.NS
AMIORG.NS
KCP.NS
SANSERA.NS
ROLEXRINGS.NS
AMBUJACEM.NS
BORORENEW.NS

In [29]:
df = pd.DataFrame(stocks_list)

In [7]:
df.columns

Index([                   'exchange',                      'symbol',
                         'marketCap',                'currentPrice',
                        'trailingPE',                 'trailingEps',
                     'profitMargins',                      'ebitda',
                      'debtToEquity', 'trailingAnnualDividendYield',
                       'priceToBook',           'financialCurrency',
           'earningsQuarterlyGrowth',                'DIFF_30_DAYS',
                       'DIFF_7_DAYS',                             0,
                                   1,                             2,
                                   3,                             4,
                                   5],
      dtype='object')

In [31]:
df[['symbol','DIFF_30_DAYS','trailingPE','debtToEquity']].sort_values(by='DIFF_30_DAYS')

           symbol  DIFF_30_DAYS  trailingPE  debtToEquity
21     FINPIPE.NS     -0.197861   16.178738         5.437
30  ROLEXRINGS.NS     -0.171290   30.337080         2.143
0        ARE&M.NS     -0.162181   20.007452         4.647
4     EXIDEIND.NS     -0.159286   39.183570        13.489
26       NOCIL.NS     -0.153405   27.567183         0.663
11   TATASTEEL.NS     -0.142364   53.256298       109.814
29     SANSERA.NS     -0.141893   37.812065        74.795
28         KCP.NS     -0.134897   13.003531        23.542
6   NATCOPHARM.NS     -0.134248   11.340273         2.912
22   TATAPOWER.NS     -0.133960   31.522670       144.120
9     TATACHEM.NS     -0.104402         NaN        28.034
20    TVSMOTOR.NS     -0.099233   57.169216       312.048
24         ACI.NS     -0.089156   34.073555         8.602
25   SHYAMMETL.NS     -0.082458   24.952112         9.954
31   AMBUJACEM.NS     -0.072450   40.882355         1.301
14       WIPRO.NS     -0.071475   25.611061        23.511
13       TECHM.NS     -0.057137   45.405480         7.566
12         TCS.NS     -0.047767   31.210003         8.836
1   BAJAJ-AUTO.NS     -0.042736   32.815727        16.523
17  ABBOTINDIA.NS     -0.036613   44.997025         1.718
19   NESTLEIND.NS     -0.029637   70.532460         9.475
8    SUNPHARMA.NS     -0.026964   38.257660         3.707
5         INFY.NS     -0.019974   29.120426         9.697
27      AMIORG.NS     -0.018786   88.769820         0.509
18  HINDUNILVR.NS     -0.010206   53.641777         3.238
23    GRAUWEIL.BO     -0.010189   28.813560         1.479
10  TATAMOTORS.NS     -0.009939    8.630457        95.362
32   BORORENEW.NS     -0.006206         NaN        64.195
16       CIPLA.NS     -0.005143   25.996752         1.621
7     RELIANCE.NS     -0.003785   25.164310        37.464
15   ZYDUSLIFE.NS     -0.002632   23.207302         0.789
2     DIVISLAB.NS      0.013967   85.627260         0.058
3      DRREDDY.NS      0.029174   19.746185        15.694

In [ ]:
df[df['trailingPE']<=28].sort_values(by='DIFF_7_DAYS')

,exchange,symbol,marketCap,currentPrice,trailingPE,trailingEps,profitMargins,ebitda,debtToEquity,trailingAnnualDividendYield,priceToBook,financialCurrency,earningsQuarterlyGrowth,DIFF_30_DAYS,DIFF_7_DAYS,0,1,2,3,4
24,NSI,FINPIPE.NS,1.392504e+11,214.75,27.925877,7.69,0.11272,6.059375e+09,10.776,NaN,2.373505,INR,0.199,0.002568,-0.032875,954000000.0,979600000.0,1153300000.0,1673200000.0,795400000.0
7,NSI,NATCOPHARM.NS,1.733606e+11,967.90,13.653548,70.89,0.33365,1.631375e+10,4.676,0.009381,3.275266,INR,2.414,0.162662,-0.027041,2127000000.0,3690000000.0,4203000000.0,2758000000.0,623000000.0
17,NSI,WIPRO.NS,2.684517e+12,510.85,23.871496,21.40,0.12436,1.652580e+11,24.507,0.001943,3.649971,INR,-0.118,0.018746,-0.018540,26463000000.0,28701000000.0,30745000000.0,30529000000.0,NaN
6,NSI,INFY.NS,6.676742e+12,1612.95,27.245775,59.20,0.15912,4.250000e+09,10.871,0.000269,694.339230,USD,-0.084,-0.039968,-0.014812,733000000.0,751000000.0,724000000.0,744000000.0,800000000.0
3,NSI,DRREDDY.NS,1.062971e+12,6302.15,20.120522,313.22,0.19243,8.097900e+10,7.411,0.006262,3.917835,INR,0.106,-0.004950,-0.005201,13789000000.0,14800000000.0,14025000000.0,9592000000.0,12471000000.0
25,NSI,TATAPOWER.NS,1.319837e+12,396.10,21.503801,18.42,0.06164,1.049663e+11,141.897,NaN,4.038705,INR,0.008,0.095106,0.011104,9530100000.0,8755300000.0,9724900000.0,7777300000.0,9450200000.0
13,NSI,TATAMTRDVR.NS,3.764246e+12,676.05,13.334319,50.70,0.04577,4.501455e+11,210.024,NaN,5.712873,INR,1.375,0.126093,0.023853,70251100000.0,37640000000.0,32028000000.0,54077900000.0,29577100000.0
12,NSI,TATAMOTORS.NS,3.764242e+12,1016.50,20.041403,50.72,0.04577,4.501455e+11,210.024,NaN,8.589803,INR,1.375,0.115072,0.029680,70251100000.0,37640000000.0,32028000000.0,54077900000.0,29577100000.0
11,NSI,TATACHEM.NS,2.993767e+11,1143.65,15.999579,71.48,0.11172,3.466250e+10,27.152,NaN,1.361297,INR,-0.596,0.208868,0.140229,1580000000.0,4280000000.0,5320000000.0,7090000000.0,3910000000.0

In [ ]:
df.sort_values(by='DIFF_7_DAYS').sort_values(by='trailingPE')

,exchange,symbol,marketCap,currentPrice,trailingPE,trailingEps,profitMargins,ebitda,debtToEquity,trailingAnnualDividendYield,priceToBook,financialCurrency,earningsQuarterlyGrowth,DIFF_30_DAYS,DIFF_7_DAYS,0,1,2,3,4
13,NSI,TATAMTRDVR.NS,3.764246e+12,676.05,13.334319,50.70,0.04577,4.501455e+11,210.024,NaN,5.712873,INR,1.375,0.126093,0.023853,70251100000.0,37640000000.0,32028000000.0,54077900000.0,29577100000.0
7,NSI,NATCOPHARM.NS,1.733606e+11,967.90,13.653548,70.89,0.33365,1.631375e+10,4.676,0.009381,3.275266,INR,2.414,0.162662,-0.027041,2127000000.0,3690000000.0,4203000000.0,2758000000.0,623000000.0
11,NSI,TATACHEM.NS,2.993767e+11,1143.65,15.999579,71.48,0.11172,3.466250e+10,27.152,NaN,1.361297,INR,-0.596,0.208868,0.140229,1580000000.0,4280000000.0,5320000000.0,7090000000.0,3910000000.0
12,NSI,TATAMOTORS.NS,3.764242e+12,1016.50,20.041403,50.72,0.04577,4.501455e+11,210.024,NaN,8.589803,INR,1.375,0.115072,0.029680,70251100000.0,37640000000.0,32028000000.0,54077900000.0,29577100000.0
3,NSI,DRREDDY.NS,1.062971e+12,6302.15,20.120522,313.22,0.19243,8.097900e+10,7.411,0.006262,3.917835,INR,0.106,-0.004950,-0.005201,13789000000.0,14800000000.0,14025000000.0,9592000000.0,12471000000.0
25,NSI,TATAPOWER.NS,1.319837e+12,396.10,21.503801,18.42,0.06164,1.049663e+11,141.897,NaN,4.038705,INR,0.008,0.095106,0.011104,9530100000.0,8755300000.0,9724900000.0,7777300000.0,9450200000.0
17,NSI,WIPRO.NS,2.684517e+12,510.85,23.871496,21.40,0.12436,1.652580e+11,24.507,0.001943,3.649971,INR,-0.118,0.018746,-0.018540,26463000000.0,28701000000.0,30745000000.0,30529000000.0,NaN
6,NSI,INFY.NS,6.676742e+12,1612.95,27.245775,59.20,0.15912,4.250000e+09,10.871,0.000269,694.339230,USD,-0.084,-0.039968,-0.014812,733000000.0,751000000.0,724000000.0,744000000.0,800000000.0
24,NSI,FINPIPE.NS,1.392504e+11,214.75,27.925877,7.69,0.11272,6.059375e+09,10.776,NaN,2.373505,INR,0.199,0.002568,-0.032875,954000000.0,979600000.0,1153300000.0,1673200000.0,795400000.0
9,NSI,RELIANCE.NS,1.996578e+13,2950.85,28.409070,103.87,0.07975,1.503867e+12,36.100,NaN,2.657518,INR,0.093,0.015888,-0.021212,172650000000.0,173940000000.0,160110000000.0,192990000000.0,157920000000.0
4,NSI,EXIDEIND.NS,2.745500e+11,319.45,31.165855,10.25,0.05359,1.707423e+10,5.927,NaN,2.174624,INR,0.008,-0.026661,-0.028289,2002300000.0,2694000000.0,2223100000.0,1801200000.0,1986100000.0
19,NSI,CIPLA.NS,1.214188e+12,1465.75,31.947472,45.88,0.14764,6.130100e+10,3.829,NaN,4.766635,INR,0.318,0.021607,-0.003908,10559000000.0,11309100000.0,9957000000.0,5256500000.0,8009600000.0
1,NSI,BAJAJ-AUTO.NS,2.417049e+12,8527.70,32.609460,261.51,0.17107,9.227678e+10,NaN,NaN,8.225615,INR,0.380,0.089113,0.039038,20326200000.0,20200500000.0,16441400000.0,17047400000.0,14727000000.0
18,NSI,ZYDUSLIFE.NS,9.997500e+11,987.70,33.779070,29.24,0.15632,4.925950e+10,0.916,NaN,5.337217,INR,0.268,0.152980,0.043805,7896000000.0,8007000000.0,10869000000.0,2966000000.0,6229000000.0
15,NSI,TCS.NS,1.516794e+13,4192.25,34.124950,122.85,0.18787,6.127200e+11,8.297,0.012372,16.821077,INR,0.020,0.017364,0.027336,110580000000.0,113420000000.0,110740000000.0,113920000000.0,108460000000.0
16,NSI,TECHM.NS,1.262655e+12,1292.30,40.753708,31.71,0.05326,5.470225e+10,9.733,0.034135,4.323158,INR,-0.606,-0.020094,0.009570,5104000000.0,4939000000.0,6925000000.0,11177000000.0,12966000000.0
10,NSI,SUNPHARMA.NS,3.801259e+12,1584.30,42.669003,37.13,0.18772,1.281485e+11,3.051,0.007844,6.354357,INR,0.165,0.032487,0.020746,25237500000.0,23755100000.0,20225400000.0,19844700000.0,21660100000.0
20,NSI,ABBOTINDIA.NS,5.785479e+11,26993.70,50.000370,539.87,0.19911,1.365813e+10,2.944,NaN,18.450140,INR,0.260,-0.052114,-0.022180,3109800000.0,3129400000.0,2902400000.0,2314200000.0,2468300000.0
21,NSI,HINDUNILVR.NS,5.611054e+12,2378.15,54.048862,44.00,0.16670,1.421525e+11,2.515,0.016737,11.098588,INR,0.014,-0.003144,-0.018105,25090000000.0,26560000000.0,25540000000.0,26000000000.0,24740000000.0
23,NSI,TVSMOTOR.NS,1.065430e+12,2242.60,65.040600,34.48,0.04386,4.920363e+10,359.015,NaN,16.860895,INR,0.591,0.101609,0.004592,4787500000.0,3863400000.0,4343000000.0,3361000000.0,3008900000.0
2,NSI,DIVISLAB.NS,9.497817e+11,3577.75,68.447490,52.27,0.18463,1.955227e+10,0.039,NaN,7.491525,INR,0.167,-0.043421,0.027410,3630000000.0,3480000000.0,3560000000.0,3209700000.0,3100000000.0
22,NSI,NESTLEIND.NS,2.517898e+12,2590.15,84.041210,30.82,0.15678,4.510490e+10,11.042,0.009075,80.747890,INR,0.071,0.056286,0.000405,9080800000.0,6983400000.0,7366400000.0,6121300000.0,NaN
0,NSI,ARE&M.NS,1.618310e+11,841.10,NaN,NaN,0.07237,1.488668e+10,1.906,NaN,NaN,INR,0.148,-0.005145,-0.008078,2547500000.0,2263200000.0,1921400000.0,1394200000.0,2218800000.0
14,NSI,TATASTEEL.NS,1.915598e+12,152.50,NaN,-2.74,-0.01432,2.014159e+11,98.811,NaN,2.089470,INR,NaN,0.109898,-0.003919,5133700000.0,-61962400000.0,6339500000.0,17048600000.0,-22238400000.0
5,NSI,GOLDBEES.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.059670,0.038040,NaN,NaN,NaN,NaN,NaN
8,NSI,PGINVIT-IV.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
finanace = _.melt(id_vars=["index"],
        var_name="Month",
        value_name="Net Income")

In [ ]:
d

{0: '3690000000.0', 1: '4203000000.0', 2: '2758000000.0', 3: '623000000.0'}

In [ ]:
df1=pd.DataFrame()

In [ ]:
df1=pd.DataFrame(stock.quarterly_income_stmt.loc['Net Income'].values.reshape(1,-1))

In [ ]:
df1

              0             1             2            3
0  3690000000.0  4203000000.0  2758000000.0  623000000.0

0.015304891983332118

In [ ]:
stock = yf.Ticker("INFY.NS")

In [ ]:
hist = stock.history(period="1mo")

In [ ]:
help(stock)

Help on Ticker in module yfinance.ticker object:

class Ticker(yfinance.base.TickerBase)
 |  Ticker(ticker, session=None, proxy=None)
 |
 |  Method resolution order:
 |      Ticker
 |      yfinance.base.TickerBase
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, ticker, session=None, proxy=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  option_chain(self, date=None, tz=None)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  actions
 |
 |  analyst_price_target
 |
 |  balance_sheet
 |
 |  balancesheet
 |
 |  calendar
 |      Returns a dictionary of events, earnings, and dividends for the ticker
 |
 |  capital_gains
 |
 |  cash_flow
 |
 |  cashflow
 |
 |  dividends
 |
 |  earnings
 |
 |  earnings_dates
 |
 |  earnings_forecasts
 |
 |  earnings_trend
 |
 |  fast_info
 |
 |  financials
 |
 |  history_metadata
 |
 |  income_stmt
 |
 |  incomestmt
 |
 |  info
 |
 |  insider_purchases
 |
 |  insider_roster_holders
 |
 |  insider_transactions
 |
 |  institutional_holders
 |
 |  isin
 |
 |  major_holders
 |
 |  mutualfund_holders
 |
 |  news
 |
 |  options
 |
 |  quarterly_balance_sheet
 |
 |  quarterly_balancesheet
 |
 |  quarterly_cash_flow
 |
 |  quarterly_cashflow
 |
 |  quarterly_earnings
 |
 |  quarterly_financials
 |
 |  quarterly_income_stmt
 |
 |  quarterly_incomestmt
 |
 |  recommendations
 |
 |  recommendations_summary
 |
 |  revenue_forecasts
 |
 |  shares
 |
 |  splits
 |
 |  sustainability
 |
 |  trend_details
 |
 |  upgrades_downgrades
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from yfinance.base.TickerBase:
 |
 |  get_actions(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_analyst_price_target(self, proxy=None, as_dict=False)
 |
 |  get_balance_sheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_balancesheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_calendar(self, proxy=None) -> dict
 |
 |  get_capital_gains(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_cash_flow(self, proxy=None, as_dict=False, pretty=False, freq='yearly') -> Union[pandas.core.frame.DataFrame, dict]
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_cashflow(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_dividends(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_earnings(self, proxy=None, as_dict=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_earnings_dates = wrapper(*args, **kwargs)
 |
 |  get_earnings_forecast(self, proxy=None, as_dict=False)
 |
 |  get_earnings_trend(self, proxy=None, as_dict=False)
 |
 |  get_fast_info(self, proxy=None)
 |
 |  get_financials(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_history_metadata(self, proxy=None) -> dict
 |
 |  get_income_stmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_incomestmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_info(self, proxy=None) -> dict
 |
 |  get_insider_purchases(self, proxy=None, as_dict=False)
 |
 |  get_insider_roster_holders(self, proxy=None, as_dict=False)
 |
 |  get_insider_transactions(self, proxy=None, as_dict=False)
 |
 |  get_institutional_holders(self, proxy=None, as_dict=False)
 |
 |  get_isin(self, proxy=None) -> Optional[str]
 |
 |  get_major_holders(self, proxy=None, as_dict=False)
 |
 |  get_mutualfund_holders(self, proxy=None, as_dict=False)
 |
 |  get_news(self, proxy=None) -> list
 |
 |  get_recommendations(self, proxy=None, as_dict=False)
 |      Returns a DataFrame with the recommendations
 |      Columns: period  strongBuy  buy  hold  sell  strongSell
 |
 |  get_recommendations_summary(self, proxy=None, as_dict=False)
 |
 |  get_rev_forecast(self, proxy=None, as_dict=False)
 |
 |  get_shares(self, proxy=None, as_dict=False) -> Union[pandas.core.frame.DataFrame, dict]
 |
 |  get_shares_full = wrapper(*args, **kwargs)
 |
 |  get_splits(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_sustainability(self, proxy=None, as_dict=False)
 |
 |  get_trend_details(self, proxy=None, as_dict=False)
 |
 |  get_upgrades_downgrades(self, proxy=None, as_dict=False)
 |      Returns a DataFrame with the recommendations changes (upgrades/downgrades)
 |      Index: date of grade
 |      Columns: firm toGrade fromGrade action
 |
 |  history = wrapper(*args, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from yfinance.base.TickerBase:
 |
 |  basic_info
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from yfinance.base.TickerBase:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [ ]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-01 00:00:00+05:30,140.000000,140.949997,139.050003,139.850006,21186105,0.0,0.0
2024-01-02 00:00:00+05:30,140.500000,140.600006,137.050003,139.600006,27764060,0.0,0.0
2024-01-03 00:00:00+05:30,139.500000,139.600006,134.350006,135.350006,45176618,0.0,0.0
2024-01-04 00:00:00+05:30,136.000000,136.350006,134.000000,134.250000,43913498,0.0,0.0
2024-01-05 00:00:00+05:30,135.000000,135.949997,132.850006,133.649994,71330190,0.0,0.0
2024-01-08 00:00:00+05:30,135.300003,135.949997,131.750000,132.000000,39559717,0.0,0.0
2024-01-09 00:00:00+05:30,133.500000,134.800003,132.500000,133.649994,30736868,0.0,0.0
2024-01-10 00:00:00+05:30,133.800003,134.699997,132.100006,134.100006,27213624,0.0,0.0
2024-01-11 00:00:00+05:30,134.850006,135.649994,134.199997,134.899994,23113349,0.0,0.0
2024-01-12 00:00:00+05:30,135.800003,136.250000,134.649994,135.300003,32883921,0.0,0.0
2024-01-15 00:00:00+05:30,136.000000,136.250000,133.949997,134.899994,34158775,0.0,0.0
2024-01-16 00:00:00+05:30,134.699997,138.500000,134.000000,137.250000,56361287,0.0,0.0
2024-01-17 00:00:00+05:30,135.449997,135.750000,131.399994,131.649994,58982971,0.0,0.0
2024-01-18 00:00:00+05:30,131.649994,132.250000,128.199997,131.000000,45273496,0.0,0.0
2024-01-19 00:00:00+05:30,132.600006,134.699997,131.600006,134.250000,32653013,0.0,0.0
2024-01-22 00:00:00+05:30,134.250000,134.250000,134.250000,134.250000,0,0.0,0.0
2024-01-23 00:00:00+05:30,134.800003,135.199997,129.300003,130.100006,35373970,0.0,0.0
2024-01-24 00:00:00+05:30,130.199997,135.550003,130.100006,135.149994,39340119,0.0,0.0
2024-01-25 00:00:00+05:30,136.500000,136.500000,132.000000,133.750000,61358839,0.0,0.0
2024-01-29 00:00:00+05:30,134.699997,135.399994,133.500000,135.000000,29745400,0.0,0.0
2024-01-30 00:00:00+05:30,135.600006,137.699997,134.500000,134.699997,35704185,0.0,0.0
2024-01-31 00:00:00+05:30,135.000000,136.699997,134.500000,135.550003,24970796,0.0,0.0

In [ ]:
!pip install nselib

Collecting nselib
  Downloading nselib-0.7-py3-none-any.whl (18 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nselib) (2.31.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nselib) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from nselib) (1.11.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2023.11.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->nselib) (1.16.0)
Installing collected packages: nselib
Successfully installed nselib-0.7

In [ ]:
from nselib import capital_market

In [ ]:
data = capital_market.price_volume_and_deliverable_position_data(symbol='TATASTEEL', period='1M')

In [ ]:
data

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,TurnoverInRs,No.ofTrades,DeliverableQty,%DlyQttoTradedQty,"ï»¿""Symbol"""
0,NaN,EQ,19-Dec-2023,136.60,136.65,137.60,134.80,135.50,135.40,135.81,"2,77,26,431","3,76,54,16,442.20","1,67,461","1,47,54,019",53.21,TATASTEEL
1,NaN,EQ,20-Dec-2023,135.40,135.90,136.15,128.75,128.85,129.75,132.87,"3,94,95,961","5,24,77,06,866.60","2,01,438","2,02,77,844",51.34,TATASTEEL
2,NaN,EQ,21-Dec-2023,129.75,128.70,131.45,127.85,131.40,131.00,130.01,"3,49,14,399","4,53,92,19,050.25","1,98,021","1,17,93,975",33.78,TATASTEEL
3,NaN,EQ,22-Dec-2023,131.00,132.40,134.75,131.75,133.45,133.55,133.44,"3,73,57,334","4,98,48,74,945.75","2,13,314","1,32,76,647",35.54,TATASTEEL
4,NaN,EQ,26-Dec-2023,133.55,134.70,136.10,134.45,135.40,135.20,135.43,"2,59,36,447","3,51,24,75,189.45","1,82,329","1,13,79,637",43.88,TATASTEEL
5,NaN,EQ,27-Dec-2023,135.20,135.85,138.90,135.50,137.00,137.20,137.40,"4,81,01,400","6,60,92,21,199.10","2,40,022","2,22,66,016",46.29,TATASTEEL
6,NaN,EQ,28-Dec-2023,137.20,138.15,138.75,136.85,138.25,138.15,137.88,"3,46,61,176","4,77,91,01,020.60","2,15,436","1,48,85,856",42.95,TATASTEEL
7,NaN,EQ,29-Dec-2023,138.15,138.60,141.25,137.15,139.30,139.60,139.52,"4,92,02,910","6,86,49,63,120.60","2,34,503","2,16,11,634",43.92,TATASTEEL
8,NaN,EQ,01-Jan-2024,139.60,140.00,140.95,139.05,139.70,139.85,140.16,"2,11,86,105","2,96,94,70,656.95","1,87,550","94,35,252",44.54,TATASTEEL
9,NaN,EQ,02-Jan-2024,139.85,140.50,140.60,137.05,139.50,139.60,139.16,"2,77,64,060","3,86,37,03,836.75","1,67,466","1,12,28,879",40.44,TATASTEEL
10,NaN,EQ,03-Jan-2024,139.60,139.50,139.60,134.35,135.00,135.35,136.44,"4,51,76,618","6,16,40,41,917.50","2,79,840","2,51,70,203",55.72,TATASTEEL
11,NaN,EQ,04-Jan-2024,135.35,136.00,136.35,134.00,134.40,134.25,134.42,"4,39,13,498","5,90,26,44,745.45","2,49,740","2,35,66,864",53.67,TATASTEEL
12,NaN,EQ,05-Jan-2024,134.25,135.00,135.95,132.85,133.70,133.65,134.34,"7,13,30,190","9,58,21,67,218.80","2,48,067","4,35,66,825",61.08,TATASTEEL
13,NaN,EQ,08-Jan-2024,133.65,135.30,135.95,131.75,132.30,132.00,133.63,"3,95,59,717","5,28,64,69,683.20","2,28,285","1,90,11,288",48.06,TATASTEEL
14,NaN,EQ,09-Jan-2024,132.00,133.50,134.80,132.50,133.85,133.65,133.81,"3,07,36,868","4,11,30,02,298.90","1,68,721","1,56,76,957",51.00,TATASTEEL
15,NaN,EQ,10-Jan-2024,133.65,133.80,134.70,132.10,134.15,134.10,133.72,"2,72,13,624","3,63,90,89,609.30","1,75,426","1,13,92,493",41.86,TATASTEEL
16,NaN,EQ,11-Jan-2024,134.10,134.85,135.65,134.20,135.10,134.90,135.05,"2,31,13,349","3,12,15,21,575.35","1,52,705","1,06,01,792",45.87,TATASTEEL
17,NaN,EQ,12-Jan-2024,134.90,135.80,136.25,134.65,135.45,135.30,135.58,"3,28,83,921","4,45,85,50,005.35","1,70,543","1,68,25,060",51.17,TATASTEEL
18,NaN,EQ,15-Jan-2024,135.30,136.00,136.25,133.95,135.00,134.90,134.79,"3,41,58,775","4,60,43,27,884.95","1,77,458","1,74,64,591",51.13,TATASTEEL
19,NaN,EQ,16-Jan-2024,134.90,134.70,138.50,134.00,137.25,137.25,136.59,"5,63,61,287","7,69,81,43,042.30","2,13,394","2,43,97,180",43.29,TATASTEEL
20,NaN,EQ,17-Jan-2024,137.25,135.45,135.75,131.40,131.80,131.65,133.28,"5,89,82,971","7,86,10,46,380.15","2,98,756","3,23,93,747",54.92,TATASTEEL
21,NaN,EQ,18-Jan-2024,131.65,131.65,132.25,128.20,131.35,131.00,130.47,"4,52,73,496","5,90,66,40,975.60","2,67,573","2,00,66,091",44.32,TATASTEEL