<a href="https://colab.research.google.com/github/illliyas/Machine-Learning/blob/master/nselib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%capture
!pip install yfinance
!pip install mplfinance
#!pip install TA-Lib

In [2]:
import yfinance as yf
import pandas as pd

/usr/local/lib/python3.10/dist-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()

In [114]:
stocks=['ARE&M.NS',
'BAJAJ-AUTO.NS',
'DIVISLAB.NS',
'DRREDDY.NS',
'EXIDEIND.NS',
'GOLDBEES.NS',
'INFY.NS',
'NATCOPHARM.NS',
'PGINVIT-IV.NS',
'RELIANCE.NS',
'SUNPHARMA.NS',
'TATACHEM.NS',
'TATAMOTORS.NS',
'TATAMTRDVR.NS',
'TATASTEEL.NS',
'TCS.NS',
'TECHM.NS',
'WIPRO.NS',
'ZYDUSLIFE.NS'
]

In [122]:
cols = ['exchange','symbol','marketCap','currentPrice','trailingPE','trailingEps','profitMargins','ebitda',
'debtToEquity',
'trailingAnnualDividendYield',
'profitMargins',
'priceToBook',
'financialCurrency',
'earningsQuarterlyGrowth']
stocks_list=[]
for s in stocks:
  print(s)
  dic={}
  stock = yf.Ticker(s)
  for c in cols:
    try:
      dic[c]=stock.info[c]
    except:
      dic[c]=None
  try:
    hist = stock.history(period="1mo")
    hist = hist.sort_index(ascending=False)
    dic['DIFF_30_DAYS']=(hist.iloc[0]['Close']-hist.iloc[-1]['Close'])/hist.iloc[-1]['Close']
    dic['DIFF_7_DAYS']=(hist.iloc[0]['Close']-hist.iloc[5]['Close'])/hist.iloc[5]['Close']
    dic.update(dict(enumerate(map(str, stock.quarterly_income_stmt.loc['Net Income'].values))))
  except:
    None
  stocks_list.append(dic)

ARE&M.NS
BAJAJ-AUTO.NS
DIVISLAB.NS
DRREDDY.NS
EXIDEIND.NS
GOLDBEES.NS
INFY.NS
NATCOPHARM.NS
PGINVIT-IV.NS
RELIANCE.NS
SUNPHARMA.NS
TATACHEM.NS
TATAMOTORS.NS
TATAMTRDVR.NS
TATASTEEL.NS
TCS.NS
TECHM.NS
WIPRO.NS
ZYDUSLIFE.NS

In [124]:
df = pd.DataFrame(stocks_list)

In [125]:
df.columns

Index([                   'exchange',                      'symbol',
                         'marketCap',                'currentPrice',
                        'trailingPE',                 'trailingEps',
                     'profitMargins',                      'ebitda',
                      'debtToEquity', 'trailingAnnualDividendYield',
                       'priceToBook',           'financialCurrency',
           'earningsQuarterlyGrowth',                'DIFF_30_DAYS',
                       'DIFF_7_DAYS',                             0,
                                   1,                             2,
                                   3,                             4],
      dtype='object')

In [130]:
df[df['trailingPE']>=28]

,exchange,symbol,marketCap,currentPrice,trailingPE,trailingEps,profitMargins,ebitda,debtToEquity,trailingAnnualDividendYield,priceToBook,financialCurrency,earningsQuarterlyGrowth,DIFF_30_DAYS,DIFF_7_DAYS,0,1,2,3,4
1,NSI,BAJAJ-AUTO.NS,2.166568e+12,7650.85,29.262030,261.46,0.17107,9.227678e+10,NaN,NaN,7.379826,INR,0.380,0.141730,0.060725,20326200000.0,20200500000.0,16441400000.0,17047400000.0,14727000000.0
2,NSI,DIVISLAB.NS,9.702892e+11,3655.00,72.678470,50.29,0.18125,1.879150e+10,0.039,NaN,7.653280,INR,-0.295,-0.066626,0.003143,3480000000.0,3560000000.0,3209700000.0,3068000000.0,NaN
4,NSI,EXIDEIND.NS,2.831350e+11,333.10,32.497562,10.25,0.05359,1.707423e+10,5.927,NaN,2.267544,INR,0.008,0.034472,0.056454,2002300000.0,2694000000.0,2223100000.0,1801200000.0,1986100000.0
6,NSI,INFY.NS,6.849134e+12,1654.70,28.064789,58.96,0.15912,4.250000e+09,10.871,0.000259,712.311650,USD,-0.084,0.066619,-0.012355,733000000.0,751000000.0,724000000.0,744000000.0,800000000.0
10,NSI,SUNPHARMA.NS,3.375018e+12,1406.65,37.853874,37.16,0.18772,1.281485e+11,3.051,0.008812,5.641833,INR,0.165,0.116167,0.017763,23755100000.0,20225400000.0,19844700000.0,21660100000.0,NaN
15,NSI,TCS.NS,1.392965e+13,3850.00,31.333930,122.87,0.18787,6.127200e+11,8.297,0.013365,15.447826,INR,0.020,0.014888,0.002134,110580000000.0,113420000000.0,110740000000.0,113920000000.0,108460000000.0
16,NSI,TECHM.NS,1.280552e+12,1311.80,41.329556,31.74,0.05326,5.470225e+10,9.733,0.032992,4.388392,INR,-0.606,0.011294,-0.068291,5104000000.0,4939000000.0,6925000000.0,11177000000.0,12966000000.0

In [37]:
finanace = _.melt(id_vars=["index"],
        var_name="Month",
        value_name="Net Income")

In [104]:
d

{0: '3690000000.0', 1: '4203000000.0', 2: '2758000000.0', 3: '623000000.0'}

In [94]:
df1=pd.DataFrame()

In [96]:
df1=pd.DataFrame(stock.quarterly_income_stmt.loc['Net Income'].values.reshape(1,-1))

In [99]:
df1

              0             1             2            3
0  3690000000.0  4203000000.0  2758000000.0  623000000.0

0.015304891983332118

In [ ]:
stock = yf.Ticker("INFY.NS")

In [ ]:
hist = stock.history(period="1mo")

In [ ]:
help(stock)

Help on Ticker in module yfinance.ticker object:

class Ticker(yfinance.base.TickerBase)
 |  Ticker(ticker, session=None, proxy=None)
 |
 |  Method resolution order:
 |      Ticker
 |      yfinance.base.TickerBase
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, ticker, session=None, proxy=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  option_chain(self, date=None, tz=None)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  actions
 |
 |  analyst_price_target
 |
 |  balance_sheet
 |
 |  balancesheet
 |
 |  calendar
 |      Returns a dictionary of events, earnings, and dividends for the ticker
 |
 |  capital_gains
 |
 |  cash_flow
 |
 |  cashflow
 |
 |  dividends
 |
 |  earnings
 |
 |  earnings_dates
 |
 |  earnings_forecasts
 |
 |  earnings_trend
 |
 |  fast_info
 |
 |  financials
 |
 |  history_metadata
 |
 |  income_stmt
 |
 |  incomestmt
 |
 |  info
 |
 |  insider_purchases
 |
 |  insider_roster_holders
 |
 |  insider_transactions
 |
 |  institutional_holders
 |
 |  isin
 |
 |  major_holders
 |
 |  mutualfund_holders
 |
 |  news
 |
 |  options
 |
 |  quarterly_balance_sheet
 |
 |  quarterly_balancesheet
 |
 |  quarterly_cash_flow
 |
 |  quarterly_cashflow
 |
 |  quarterly_earnings
 |
 |  quarterly_financials
 |
 |  quarterly_income_stmt
 |
 |  quarterly_incomestmt
 |
 |  recommendations
 |
 |  recommendations_summary
 |
 |  revenue_forecasts
 |
 |  shares
 |
 |  splits
 |
 |  sustainability
 |
 |  trend_details
 |
 |  upgrades_downgrades
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from yfinance.base.TickerBase:
 |
 |  get_actions(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_analyst_price_target(self, proxy=None, as_dict=False)
 |
 |  get_balance_sheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_balancesheet(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_calendar(self, proxy=None) -> dict
 |
 |  get_capital_gains(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_cash_flow(self, proxy=None, as_dict=False, pretty=False, freq='yearly') -> Union[pandas.core.frame.DataFrame, dict]
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_cashflow(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_dividends(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_earnings(self, proxy=None, as_dict=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_earnings_dates = wrapper(*args, **kwargs)
 |
 |  get_earnings_forecast(self, proxy=None, as_dict=False)
 |
 |  get_earnings_trend(self, proxy=None, as_dict=False)
 |
 |  get_fast_info(self, proxy=None)
 |
 |  get_financials(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_history_metadata(self, proxy=None) -> dict
 |
 |  get_income_stmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |      :Parameters:
 |          as_dict: bool
 |              Return table as Python dict
 |              Default is False
 |          pretty: bool
 |              Format row names nicely for readability
 |              Default is False
 |          freq: str
 |              "yearly" or "quarterly"
 |              Default is "yearly"
 |          proxy: str
 |              Optional. Proxy server URL scheme
 |              Default is None
 |
 |  get_incomestmt(self, proxy=None, as_dict=False, pretty=False, freq='yearly')
 |
 |  get_info(self, proxy=None) -> dict
 |
 |  get_insider_purchases(self, proxy=None, as_dict=False)
 |
 |  get_insider_roster_holders(self, proxy=None, as_dict=False)
 |
 |  get_insider_transactions(self, proxy=None, as_dict=False)
 |
 |  get_institutional_holders(self, proxy=None, as_dict=False)
 |
 |  get_isin(self, proxy=None) -> Optional[str]
 |
 |  get_major_holders(self, proxy=None, as_dict=False)
 |
 |  get_mutualfund_holders(self, proxy=None, as_dict=False)
 |
 |  get_news(self, proxy=None) -> list
 |
 |  get_recommendations(self, proxy=None, as_dict=False)
 |      Returns a DataFrame with the recommendations
 |      Columns: period  strongBuy  buy  hold  sell  strongSell
 |
 |  get_recommendations_summary(self, proxy=None, as_dict=False)
 |
 |  get_rev_forecast(self, proxy=None, as_dict=False)
 |
 |  get_shares(self, proxy=None, as_dict=False) -> Union[pandas.core.frame.DataFrame, dict]
 |
 |  get_shares_full = wrapper(*args, **kwargs)
 |
 |  get_splits(self, proxy=None) -> pandas.core.series.Series
 |
 |  get_sustainability(self, proxy=None, as_dict=False)
 |
 |  get_trend_details(self, proxy=None, as_dict=False)
 |
 |  get_upgrades_downgrades(self, proxy=None, as_dict=False)
 |      Returns a DataFrame with the recommendations changes (upgrades/downgrades)
 |      Index: date of grade
 |      Columns: firm toGrade fromGrade action
 |
 |  history = wrapper(*args, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from yfinance.base.TickerBase:
 |
 |  basic_info
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from yfinance.base.TickerBase:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [ ]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-01 00:00:00+05:30,140.000000,140.949997,139.050003,139.850006,21186105,0.0,0.0
2024-01-02 00:00:00+05:30,140.500000,140.600006,137.050003,139.600006,27764060,0.0,0.0
2024-01-03 00:00:00+05:30,139.500000,139.600006,134.350006,135.350006,45176618,0.0,0.0
2024-01-04 00:00:00+05:30,136.000000,136.350006,134.000000,134.250000,43913498,0.0,0.0
2024-01-05 00:00:00+05:30,135.000000,135.949997,132.850006,133.649994,71330190,0.0,0.0
2024-01-08 00:00:00+05:30,135.300003,135.949997,131.750000,132.000000,39559717,0.0,0.0
2024-01-09 00:00:00+05:30,133.500000,134.800003,132.500000,133.649994,30736868,0.0,0.0
2024-01-10 00:00:00+05:30,133.800003,134.699997,132.100006,134.100006,27213624,0.0,0.0
2024-01-11 00:00:00+05:30,134.850006,135.649994,134.199997,134.899994,23113349,0.0,0.0
2024-01-12 00:00:00+05:30,135.800003,136.250000,134.649994,135.300003,32883921,0.0,0.0
2024-01-15 00:00:00+05:30,136.000000,136.250000,133.949997,134.899994,34158775,0.0,0.0
2024-01-16 00:00:00+05:30,134.699997,138.500000,134.000000,137.250000,56361287,0.0,0.0
2024-01-17 00:00:00+05:30,135.449997,135.750000,131.399994,131.649994,58982971,0.0,0.0
2024-01-18 00:00:00+05:30,131.649994,132.250000,128.199997,131.000000,45273496,0.0,0.0
2024-01-19 00:00:00+05:30,132.600006,134.699997,131.600006,134.250000,32653013,0.0,0.0
2024-01-22 00:00:00+05:30,134.250000,134.250000,134.250000,134.250000,0,0.0,0.0
2024-01-23 00:00:00+05:30,134.800003,135.199997,129.300003,130.100006,35373970,0.0,0.0
2024-01-24 00:00:00+05:30,130.199997,135.550003,130.100006,135.149994,39340119,0.0,0.0
2024-01-25 00:00:00+05:30,136.500000,136.500000,132.000000,133.750000,61358839,0.0,0.0
2024-01-29 00:00:00+05:30,134.699997,135.399994,133.500000,135.000000,29745400,0.0,0.0
2024-01-30 00:00:00+05:30,135.600006,137.699997,134.500000,134.699997,35704185,0.0,0.0
2024-01-31 00:00:00+05:30,135.000000,136.699997,134.500000,135.550003,24970796,0.0,0.0

In [ ]:
!pip install nselib

Collecting nselib
  Downloading nselib-0.7-py3-none-any.whl (18 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nselib) (2.31.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nselib) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from nselib) (1.11.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2023.11.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->nselib) (1.16.0)
Installing collected packages: nselib
Successfully installed nselib-0.7

In [ ]:
from nselib import capital_market

In [ ]:
data = capital_market.price_volume_and_deliverable_position_data(symbol='TATASTEEL', period='1M')

In [ ]:
data

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,TurnoverInRs,No.ofTrades,DeliverableQty,%DlyQttoTradedQty,"ï»¿""Symbol"""
0,NaN,EQ,19-Dec-2023,136.60,136.65,137.60,134.80,135.50,135.40,135.81,"2,77,26,431","3,76,54,16,442.20","1,67,461","1,47,54,019",53.21,TATASTEEL
1,NaN,EQ,20-Dec-2023,135.40,135.90,136.15,128.75,128.85,129.75,132.87,"3,94,95,961","5,24,77,06,866.60","2,01,438","2,02,77,844",51.34,TATASTEEL
2,NaN,EQ,21-Dec-2023,129.75,128.70,131.45,127.85,131.40,131.00,130.01,"3,49,14,399","4,53,92,19,050.25","1,98,021","1,17,93,975",33.78,TATASTEEL
3,NaN,EQ,22-Dec-2023,131.00,132.40,134.75,131.75,133.45,133.55,133.44,"3,73,57,334","4,98,48,74,945.75","2,13,314","1,32,76,647",35.54,TATASTEEL
4,NaN,EQ,26-Dec-2023,133.55,134.70,136.10,134.45,135.40,135.20,135.43,"2,59,36,447","3,51,24,75,189.45","1,82,329","1,13,79,637",43.88,TATASTEEL
5,NaN,EQ,27-Dec-2023,135.20,135.85,138.90,135.50,137.00,137.20,137.40,"4,81,01,400","6,60,92,21,199.10","2,40,022","2,22,66,016",46.29,TATASTEEL
6,NaN,EQ,28-Dec-2023,137.20,138.15,138.75,136.85,138.25,138.15,137.88,"3,46,61,176","4,77,91,01,020.60","2,15,436","1,48,85,856",42.95,TATASTEEL
7,NaN,EQ,29-Dec-2023,138.15,138.60,141.25,137.15,139.30,139.60,139.52,"4,92,02,910","6,86,49,63,120.60","2,34,503","2,16,11,634",43.92,TATASTEEL
8,NaN,EQ,01-Jan-2024,139.60,140.00,140.95,139.05,139.70,139.85,140.16,"2,11,86,105","2,96,94,70,656.95","1,87,550","94,35,252",44.54,TATASTEEL
9,NaN,EQ,02-Jan-2024,139.85,140.50,140.60,137.05,139.50,139.60,139.16,"2,77,64,060","3,86,37,03,836.75","1,67,466","1,12,28,879",40.44,TATASTEEL
10,NaN,EQ,03-Jan-2024,139.60,139.50,139.60,134.35,135.00,135.35,136.44,"4,51,76,618","6,16,40,41,917.50","2,79,840","2,51,70,203",55.72,TATASTEEL
11,NaN,EQ,04-Jan-2024,135.35,136.00,136.35,134.00,134.40,134.25,134.42,"4,39,13,498","5,90,26,44,745.45","2,49,740","2,35,66,864",53.67,TATASTEEL
12,NaN,EQ,05-Jan-2024,134.25,135.00,135.95,132.85,133.70,133.65,134.34,"7,13,30,190","9,58,21,67,218.80","2,48,067","4,35,66,825",61.08,TATASTEEL
13,NaN,EQ,08-Jan-2024,133.65,135.30,135.95,131.75,132.30,132.00,133.63,"3,95,59,717","5,28,64,69,683.20","2,28,285","1,90,11,288",48.06,TATASTEEL
14,NaN,EQ,09-Jan-2024,132.00,133.50,134.80,132.50,133.85,133.65,133.81,"3,07,36,868","4,11,30,02,298.90","1,68,721","1,56,76,957",51.00,TATASTEEL
15,NaN,EQ,10-Jan-2024,133.65,133.80,134.70,132.10,134.15,134.10,133.72,"2,72,13,624","3,63,90,89,609.30","1,75,426","1,13,92,493",41.86,TATASTEEL
16,NaN,EQ,11-Jan-2024,134.10,134.85,135.65,134.20,135.10,134.90,135.05,"2,31,13,349","3,12,15,21,575.35","1,52,705","1,06,01,792",45.87,TATASTEEL
17,NaN,EQ,12-Jan-2024,134.90,135.80,136.25,134.65,135.45,135.30,135.58,"3,28,83,921","4,45,85,50,005.35","1,70,543","1,68,25,060",51.17,TATASTEEL
18,NaN,EQ,15-Jan-2024,135.30,136.00,136.25,133.95,135.00,134.90,134.79,"3,41,58,775","4,60,43,27,884.95","1,77,458","1,74,64,591",51.13,TATASTEEL
19,NaN,EQ,16-Jan-2024,134.90,134.70,138.50,134.00,137.25,137.25,136.59,"5,63,61,287","7,69,81,43,042.30","2,13,394","2,43,97,180",43.29,TATASTEEL
20,NaN,EQ,17-Jan-2024,137.25,135.45,135.75,131.40,131.80,131.65,133.28,"5,89,82,971","7,86,10,46,380.15","2,98,756","3,23,93,747",54.92,TATASTEEL
21,NaN,EQ,18-Jan-2024,131.65,131.65,132.25,128.20,131.35,131.00,130.47,"4,52,73,496","5,90,66,40,975.60","2,67,573","2,00,66,091",44.32,TATASTEEL