<a href="https://colab.research.google.com/github/illliyas/Machine-Learning/blob/master/nselib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nselib

Collecting nselib
  Downloading nselib-0.7-py3-none-any.whl (18 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nselib) (2.31.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nselib) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from nselib) (1.11.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2023.11.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->nselib) (1.16.0)
Installing collected packages: nselib
Successfully installed nselib-0.7

In [2]:
from nselib import capital_market

In [5]:
data = capital_market.price_volume_and_deliverable_position_data(symbol='TATASTEEL', period='1M')

In [6]:
data

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,TurnoverInRs,No.ofTrades,DeliverableQty,%DlyQttoTradedQty,"ï»¿""Symbol"""
0,NaN,EQ,19-Dec-2023,136.60,136.65,137.60,134.80,135.50,135.40,135.81,"2,77,26,431","3,76,54,16,442.20","1,67,461","1,47,54,019",53.21,TATASTEEL
1,NaN,EQ,20-Dec-2023,135.40,135.90,136.15,128.75,128.85,129.75,132.87,"3,94,95,961","5,24,77,06,866.60","2,01,438","2,02,77,844",51.34,TATASTEEL
2,NaN,EQ,21-Dec-2023,129.75,128.70,131.45,127.85,131.40,131.00,130.01,"3,49,14,399","4,53,92,19,050.25","1,98,021","1,17,93,975",33.78,TATASTEEL
3,NaN,EQ,22-Dec-2023,131.00,132.40,134.75,131.75,133.45,133.55,133.44,"3,73,57,334","4,98,48,74,945.75","2,13,314","1,32,76,647",35.54,TATASTEEL
4,NaN,EQ,26-Dec-2023,133.55,134.70,136.10,134.45,135.40,135.20,135.43,"2,59,36,447","3,51,24,75,189.45","1,82,329","1,13,79,637",43.88,TATASTEEL
5,NaN,EQ,27-Dec-2023,135.20,135.85,138.90,135.50,137.00,137.20,137.40,"4,81,01,400","6,60,92,21,199.10","2,40,022","2,22,66,016",46.29,TATASTEEL
6,NaN,EQ,28-Dec-2023,137.20,138.15,138.75,136.85,138.25,138.15,137.88,"3,46,61,176","4,77,91,01,020.60","2,15,436","1,48,85,856",42.95,TATASTEEL
7,NaN,EQ,29-Dec-2023,138.15,138.60,141.25,137.15,139.30,139.60,139.52,"4,92,02,910","6,86,49,63,120.60","2,34,503","2,16,11,634",43.92,TATASTEEL
8,NaN,EQ,01-Jan-2024,139.60,140.00,140.95,139.05,139.70,139.85,140.16,"2,11,86,105","2,96,94,70,656.95","1,87,550","94,35,252",44.54,TATASTEEL
9,NaN,EQ,02-Jan-2024,139.85,140.50,140.60,137.05,139.50,139.60,139.16,"2,77,64,060","3,86,37,03,836.75","1,67,466","1,12,28,879",40.44,TATASTEEL
10,NaN,EQ,03-Jan-2024,139.60,139.50,139.60,134.35,135.00,135.35,136.44,"4,51,76,618","6,16,40,41,917.50","2,79,840","2,51,70,203",55.72,TATASTEEL
11,NaN,EQ,04-Jan-2024,135.35,136.00,136.35,134.00,134.40,134.25,134.42,"4,39,13,498","5,90,26,44,745.45","2,49,740","2,35,66,864",53.67,TATASTEEL
12,NaN,EQ,05-Jan-2024,134.25,135.00,135.95,132.85,133.70,133.65,134.34,"7,13,30,190","9,58,21,67,218.80","2,48,067","4,35,66,825",61.08,TATASTEEL
13,NaN,EQ,08-Jan-2024,133.65,135.30,135.95,131.75,132.30,132.00,133.63,"3,95,59,717","5,28,64,69,683.20","2,28,285","1,90,11,288",48.06,TATASTEEL
14,NaN,EQ,09-Jan-2024,132.00,133.50,134.80,132.50,133.85,133.65,133.81,"3,07,36,868","4,11,30,02,298.90","1,68,721","1,56,76,957",51.00,TATASTEEL
15,NaN,EQ,10-Jan-2024,133.65,133.80,134.70,132.10,134.15,134.10,133.72,"2,72,13,624","3,63,90,89,609.30","1,75,426","1,13,92,493",41.86,TATASTEEL
16,NaN,EQ,11-Jan-2024,134.10,134.85,135.65,134.20,135.10,134.90,135.05,"2,31,13,349","3,12,15,21,575.35","1,52,705","1,06,01,792",45.87,TATASTEEL
17,NaN,EQ,12-Jan-2024,134.90,135.80,136.25,134.65,135.45,135.30,135.58,"3,28,83,921","4,45,85,50,005.35","1,70,543","1,68,25,060",51.17,TATASTEEL
18,NaN,EQ,15-Jan-2024,135.30,136.00,136.25,133.95,135.00,134.90,134.79,"3,41,58,775","4,60,43,27,884.95","1,77,458","1,74,64,591",51.13,TATASTEEL
19,NaN,EQ,16-Jan-2024,134.90,134.70,138.50,134.00,137.25,137.25,136.59,"5,63,61,287","7,69,81,43,042.30","2,13,394","2,43,97,180",43.29,TATASTEEL
20,NaN,EQ,17-Jan-2024,137.25,135.45,135.75,131.40,131.80,131.65,133.28,"5,89,82,971","7,86,10,46,380.15","2,98,756","3,23,93,747",54.92,TATASTEEL
21,NaN,EQ,18-Jan-2024,131.65,131.65,132.25,128.20,131.35,131.00,130.47,"4,52,73,496","5,90,66,40,975.60","2,67,573","2,00,66,091",44.32,TATASTEEL