<a href="https://colab.research.google.com/github/illliyas/Machine-Learning/blob/master/us_stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%capture
!pip install yfinance
!pip install mplfinance
#!pip install TA-Lib

In [2]:
import yfinance as yf
import pandas as pd

In [74]:
stocks=['AAPL','MSFT','GOOGL',
'PG',
'MRK',
'KO',
'ABT',
'AMAT',
'PCAR',
'HPQ',
'ON',
'LLY',
'HON',
'TEL',
'KHC',
'SKX',
'GIS',
'TM',
'V',
'MCD',
'HMC']

In [75]:
cols = ['exchange','symbol','marketCap','currentPrice','trailingPE','trailingEps','profitMargins','ebitda',
'debtToEquity',
'trailingAnnualDividendYield',
'profitMargins',
'priceToBook',
'financialCurrency',
'earningsQuarterlyGrowth'
]
stocks_list=[]
for s in stocks:
  print(s)
  dic={}
  stock = yf.Ticker(s)
  stock_info = stock.get_info()
  for c in cols:
    try:
      dic[c]=stock_info[c]
    except:
      None
  try:
    hist = stock.history(period="1mo")
    hist = hist.sort_index(ascending=False)
    dic['DIFF_30_DAYS']=(hist.iloc[0]['Close']-hist.iloc[-1]['Close'])/hist.iloc[-1]['Close']
    dic['DIFF_7_DAYS']=(hist.iloc[0]['Close']-hist.iloc[5]['Close'])/hist.iloc[5]['Close']
    dic.update(dict(enumerate(map(str, stock.quarterly_income_stmt.loc['Net Income'].values))))
  except:
    None
  stocks_list.append(dic)

AAPL
MSFT
GOOGL
PG
MRK
KO
ABT
AMAT
PCAR
HPQ
ON
LLY
HON
TEL
KHC
SKX
GIS
TM
V
MCD
HMC

In [76]:
df = pd.DataFrame(stocks_list)

In [81]:
df[[0, 1,2,3,4]] = df[[0, 1,2,3,4]].apply(pd.to_numeric)

In [84]:
df['Q_PRE_Y_Q_VAR'] = (df[0]-df[4])/df[4]
df['Q_PRE_Q_VAR'] = (df[0]-df[1])/df[1]

In [91]:
df[((df['Q_PRE_Y_Q_VAR']>0) & (df['trailingPE']<=28))].sort_values('DIFF_30_DAYS')[['symbol','trailingPE','debtToEquity','DIFF_7_DAYS','DIFF_30_DAYS','Q_PRE_Y_Q_VAR','Q_PRE_Q_VAR']]

,symbol,trailingPE,debtToEquity,DIFF_7_DAYS,DIFF_30_DAYS,Q_PRE_Y_Q_VAR,Q_PRE_Q_VAR
7,AMAT,21.195480,35.409,0.056491,-0.109038,0.092949,-0.009872
2,GOOGL,22.677189,9.549,0.062874,-0.050401,0.285878,-0.001817
17,TM,6.744355,105.806,0.000852,-0.040664,0.016757,0.336433
20,HMC,6.320000,82.984,0.002220,-0.026794,0.087011,0.661272
13,TEL,13.059982,33.124,0.007319,-0.026563,0.085227,0.059150
12,HON,23.365295,165.725,0.017498,NaN,0.038332,0.055366

In [92]:
df

,exchange,symbol,marketCap,currentPrice,trailingPE,trailingEps,profitMargins,ebitda,debtToEquity,trailingAnnualDividendYield,...,DIFF_7_DAYS,0,1,2,3,4,5,6,Q_PRE_Y_Q_VAR,Q_PRE_Q_VAR
0,NMS,AAPL,3288951160832,216.32,33.905956,6.38,0.26441,131781001216,151.862,0.004360,...,-0.020778,2.144800e+10,2.363600e+10,3.391600e+10,2.295600e+10,1.988100e+10,nan,nan,0.078819,-0.092571
1,NMS,MSFT,3206167396352,431.34,36.492386,11.82,0.35956,129433001984,36.447,0.006967,...,0.063147,2.203600e+10,2.193900e+10,2.187000e+10,2.229100e+10,2.008100e+10,nan,nan,0.097356,0.004421
2,NMS,GOOGL,1950918639616,158.06,22.677189,6.97,0.26702,115478003712,9.549,0.001270,...,0.062874,2.361900e+10,2.366200e+10,2.068700e+10,1.968900e+10,1.836800e+10,nan,NaN,0.285878,-0.001817
3,NYQ,PG,416462635008,177.24,29.393034,6.03,0.17705,23843999744,66.706,0.021996,...,0.006702,3.137000e+09,3.754000e+09,3.468000e+09,4.521000e+09,3.384000e+09,nan,nan,-0.072991,-0.164358
4,NYQ,MRK,299006197760,117.96,21.447273,5.50,0.21985,23631998976,86.574,0.026067,...,0.028933,5.455000e+09,4.762000e+09,-1.226000e+09,4.745000e+09,-5.975000e+09,NaN,NaN,-1.912971,0.145527
5,NYQ,KO,310741630976,72.10,29.072580,2.48,0.22916,14906999808,164.398,0.026467,...,0.010359,2.411000e+09,3.177000e+09,1.973000e+09,3.087000e+09,2.547000e+09,nan,nan,-0.053396,-0.241108
6,NYQ,ABT,204664438784,117.63,36.759373,3.20,0.13645,10570999808,37.525,0.018557,...,0.010307,1.302000e+09,1.225000e+09,1.594000e+09,1.436000e+09,1.375000e+09,nan,NaN,-0.053091,0.062857
7,NMS,AMAT,154641694720,187.58,21.195480,8.85,0.27743,8204000256,35.409,0.007640,...,0.056491,1.705000e+09,1.722000e+09,2.019000e+09,2.004000e+09,1.560000e+09,nan,nan,0.092949,-0.009872
8,NMS,PCAR,50168045568,95.70,10.148461,9.43,0.14066,6295099904,81.700,0.011669,...,0.007687,1.122600e+09,1.195300e+09,1.417300e+09,1.228500e+09,1.221100e+09,NaN,NaN,-0.080665,-0.060822
9,NYQ,HPQ,32524652544,33.76,11.845614,2.85,0.05332,5045000192,NaN,0.032683,...,-0.004075,6.400000e+08,6.070000e+08,6.220000e+08,9.740000e+08,7.660000e+08,nan,NaN,-0.164491,0.054366
10,NMS,ON,30143412224,70.37,16.029613,4.39,0.24838,2986200064,43.602,NaN,...,0.014123,3.382000e+08,4.530000e+08,5.627000e+08,5.827000e+08,5.766000e+08,nan,nan,-0.413458,-0.253422
11,NYQ,LLY,831579422720,923.54,113.596550,8.13,0.18863,15501899776,212.883,0.005261,...,0.016812,2.967000e+09,2.242900e+09,2.189700e+09,-5.740000e+07,1.763200e+09,nan,nan,0.682736,0.322841
12,NMS,HON,132974649344,204.68,23.365295,8.76,0.15493,9048000512,165.725,0.020916,...,0.017498,1.544000e+09,1.463000e+09,1.263000e+09,1.514000e+09,1.487000e+09,nan,nan,0.038332,0.055366
13,NYQ,TEL,44335706112,145.88,13.059982,11.17,0.21939,3688999936,33.124,0.016594,...,0.007319,5.730000e+08,5.410000e+08,1.803000e+09,5.520000e+08,5.280000e+08,nan,NaN,0.085227,0.059150
14,NMS,KHC,43079524352,35.63,22.839745,1.56,0.07303,6493000192,40.656,0.044956,...,-0.011650,1.020000e+08,8.010000e+08,7.570000e+08,2.620000e+08,1.000000e+09,nan,nan,-0.898000,-0.872659
15,NYQ,SKX,10337996800,67.86,18.193030,3.73,0.06903,1048195968,38.423,NaN,...,0.027870,1.403020e+08,2.066220e+08,8.718200e+07,1.454150e+08,1.527590e+08,NaN,NaN,-0.081547,-0.320973
16,NYQ,GIS,41540550656,74.63,17.315544,4.31,0.12573,4321399808,138.002,0.032017,...,-0.006920,5.575000e+08,6.701000e+08,5.955000e+08,6.735000e+08,6.149000e+08,nan,NaN,-0.093349,-0.168035
17,NYQ,TM,237374750720,176.23,6.744355,26.13,0.10708,7282626134016,105.806,0.427618,...,0.000852,1.333347e+12,9.976910e+11,1.357814e+12,1.278056e+12,1.311372e+12,nan,nan,0.016757,0.336433
18,NYQ,V,565239283712,290.48,30.771189,9.44,0.54717,24384000000,51.856,0.007239,...,0.017051,4.872000e+09,4.663000e+09,4.890000e+09,4.681000e+09,4.156000e+09,NaN,NaN,0.172281,0.044821
19,NYQ,MCD,212828487680,296.69,25.979860,11.42,0.32250,13770500096,NaN,0.022021,...,0.018538,2.022000e+09,1.929000e+09,2.039000e+09,2.317100e+09,2.310000e+09,nan,NaN,-0.124675,0.048212
20,NYQ,HMC,50084737024,31.60,6.320000,5.00,0.05369,2791233028096,82.984,2.160788,...,0.002220,3.946600e+11,2.375650e+11,2.533080e+11,2.532320e+11,3.630690e+11,nan,NaN,0.087011,0.661272

In [ ]:
finanace = _.melt(id_vars=["index"],
        var_name="Month",
        value_name="Net Income")

In [ ]:
d

{0: '3690000000.0', 1: '4203000000.0', 2: '2758000000.0', 3: '623000000.0'}

In [ ]:
df1=pd.DataFrame()

In [ ]:
df1=pd.DataFrame(stock.quarterly_income_stmt.loc['Net Income'].values.reshape(1,-1))

In [ ]:
df1

              0             1             2            3
0  3690000000.0  4203000000.0  2758000000.0  623000000.0

0.015304891983332118

In [ ]:
stock = yf.Ticker("INFY.NS")